branches:
  - main

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
        - Cargo.toml
        - Cargo.lock
      message: "chore(release): set `Cargo.toml` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - - '@semantic-release/exec'
    - verifyReleaseCmd: "echo \"export SIDECAR_VERSION=${nextRelease.version}\" >> /tmp/sidecar.env"